# Generated by Django 4.2.24 on 2025-12-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_shipping_address',
            field=models.TextField(blank=True, help_text='Used to prefill your details at checkout.', verbose_name='Default shipping address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone number'),
        ),
    ]
