# Generated by Django 4.2.24 on 2025-12-24 22:59

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_default_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_shipping_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, max_length=40, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Shipping full name'),
        ),
    ]
