# Generated by Django 4.2.24 on 2025-12-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('order_year', 'order_seq'), name='uniq_order_year_seq'),
        ),
    ]
